### ISSUE TITLE
建议在仓库描述添加站点地址

### ISSUE THREAD

**Issue by W1ndys** [DuckDuckStudio/yazicbs.github.io#23]
![image](https://github.com/DuckDuckStudio/yazicbs.github.io/assets/109416673/02f1923f-acb4-4565-83e6-b6f92698361c)

**Comment by DuckDuckStudio** [comment]
当时也没想到真会有人看（还是看仓库页面）。
已添加，感谢支持
![image](https://github.com/DuckDuckStudio/yazicbs.github.io/assets/89643991/c6f6dee9-c5b0-49b0-8bfb-4f3dba53c49b)

**Comment by W1ndys** [comment]
看到这里真的有共鸣了

![image](https://github.com/DuckDuckStudio/yazicbs.github.io/assets/109416673/53dd97ff-7b15-4bb0-9e02-5f120f65cf2c)

我也是一个文档页面的维护者（独立维护），但我是基于Mkdocs架构（hhh太菜了不会自己设计）

我是从[这里](https://github.com/1c7/chinese-independent-developer?tab=readme-ov-file#2024%E5%B9%B44%E6%9C%889%E6%97%A5%E6%B7%BB%E5%8A%A0)发现了你开发的工具箱，然后顺藤摸瓜进到了你的Github主页💪💪💪
