### ISSUE TITLE
[Feat] 手机页面控制台

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/yazicbs.github.io#43]
### 选择一个类别

控制台输出

### 对新功能/建议的描述

在手机上的页面可以通过特殊操作查看控制台输出

### 为什么需要实现此功能

可以查看只有在手机上才会出现的问题

### 对于实施该功能的方法的建议

/

**Comment by DuckDuckStudio** [comment]
清理工作区

**Comment by Luna-Grace** [comment]
添加一个函数来debug？

**Comment by fjwxzde** [comment]
See https://duckduckstudio.github.io/yazicbs.github.io/zh_cn/debug
