### ISSUE TITLE
部分地区没有翻译

### ISSUE THREAD

**Issue by Luna-Grace** [DuckDuckStudio/yazicbs.github.io#56]
![image](https://github.com/user-attachments/assets/0e645a1a-eabe-48b3-8667-5fd6c3482616)

![image](https://github.com/user-attachments/assets/273134e6-8867-417c-aaf1-7b3beb70065f)

**Comment by Luna-Grace** [comment]
这两个似乎不是市级地址，可能是：

- 马巷，厦门
- 金融街

**Comment by DuckDuckStudio** [comment]
你提到的情况时`region`就是城市名，但当`city`是城市名是`region`就是省...

**Comment by Luna-Grace** [comment]
要不就先保持现状，有其他市级地区没翻译再提issue
