### ISSUE TITLE
[Feat]: 想和你聊聊呀

### ISSUE THREAD

**Issue by TylerSean** [DuckDuckStudio/yazicbs.github.io#58]
### 选择一个类别

其他

### 对新功能/建议的描述

看到了你的博客，很想帮助你，但是我给你B站发了私信，QQ也试图添加了你的好友，都没有得到回应。我是中国科学院的研究生，或许你可以相信我，跟我聊聊吗？

### 为什么需要实现此功能

111

### 对于实施该功能的方法的建议

111

**Comment by DuckDuckStudio** [comment]
我不清楚怎样可以帮到我。

想去看，没号
去咨询，说没事

> 对不起，这几天都没看QQ，没看到消息。

**Comment by DuckDuckStudio** [comment]
感谢关心

**Comment by TylerSean** [comment]
在吗，QQ给你发消息了
