### ISSUE TITLE
[BUG]: Uncaught TypeError: {(intermediate value)} is not a function.

### ISSUE THREAD

**Issue by Luna-Grace** [DuckDuckStudio/yazicbs.github.io#69]
### 在继续之前，请确认以下内容

- [X] 我已经搜索过已存在的问题，并没有存在相同的正在进行中/重复/已解决的问题
- [X] 我知道由于作者精力有限，可能不会处理手机端的显示错误

### 选择一个问题类别

JS相关问题

### 描述你遇到的问题

控制台中显示错误信息，但显示没有问题。
![image](https://github.com/user-attachments/assets/c4a41b16-7255-4941-90f8-dd9809fd5a88)

### 描述如何重现你遇到的问题

1. 访问主页
2. F12

### 实际行为

Uncaught TypeError: {(intermediate value)} is not a function
    at index.html:117:13

### 预期行为

没有错误

### 确认相关信息

```raw
/
```

### 屏幕截图或日志

/

**Comment by DuckDuckStudio** [comment]
@fjwxzde run test

**Comment by fjwxzde** [comment]
可以复现
